default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: keerthi
  password: Rachubai123*
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_web_app_development

test:
  <<: *default
  database: todo_web_app_test

production:
  <<: *default
  database: todo_web_app_production
  username: todo_web_app
  password: <%= ENV['TODO_WEB_APP_DATABASE_PASSWORD'] %>